Algoritmo "LISTA II - Q8"
Var

nome: caractere
peso, altura, IMC: real

Inicio
      escreval(">>Cálculo do Índice de Massa Corpórea (IMC)<<")
      escreval
      escreval("Digite seu nome")
      leia(nome)
      
      escreval("Digite seu peso")
      leia(peso)
      
      escreval("Digite sua altura")
      leia(altura)
      
      IMC <- peso/(altura^2)
      
      escreval("Seu Índice de Massa Corpórea (IMC) =",IMC)
      
      
Fimalgoritmo