(function() {
  angular.module('i18nmessages', []).value('i18nmessages', {
    'greetings.hello': 'Hello in Japanese',
    'subtitle': 'Light weight code running container',
    'navbar.newcode': 'New code',
    'navbar.new': 'New',
    'navbar.online': 'online',
    'navbar.code': 'code',
    'navbar.onlinecoding': 'online compiler',
    'navbar.recentcode': 'Recent codes',
    'navbar.recent': 'Recent',
    'navbar.terminal': 'Terminal',
    'navbar.paizacloud': 'WebDev',
    'input': 'Input',
    'run': 'Run',
    'project.input': 'Input',
    'project.output': 'Output',
    'project.error': 'Runtime error',
    'project.build_stderr': 'Build error',
    'ask_sign_in': 'Please sign in to use this feature.',
    'ask_sign_in_github': 'Please sign in or connect account to GitHub to use this feature.',
    'not_owner': 'Only owner can use this feature.',
    'code_information': 'Code information',
    'editor_preferences': 'Editor preferences',
    'scheduling': 'Task scheduling',
    'link_gist': 'Linked to GitHub Gist',
    'no_link_gist': 'Not linked to GitHub Gist',
    'favorited': 'Favorited',
    'no_favorited': 'Not favorited',
    'featured': 'Featured',
    'featured_codes': 'Featured codes',
    'live_update': 'Real-time collaboration(Experimental)',
    'public': 'In public',
    'private': 'In private',
    'share_embed': 'Share or Embed',
    'share': 'Share',
    'embed': 'Embed',
    'my_codes': 'My codes',
    'favorites': 'Favorites',
    'all': 'All',
    'email': 'E-mail',
    'password': 'Password',
    'password_confirm': 'Password confirmation',
    'remember_me': 'Remember me',
    'owner': 'Owner',
    'not_owner': 'You are not the owner of this code.',
    'confirm_leave': 'Your code is not saved. Are you sure you want to leave this page?',
    'comments': 'Comments',
    'comment_placeholder': 'Looks good for you ?'
  });

}).call(this);
